circleci: add failing circle config
securedrop-bot/securedrop-test pull request #3
Opened 2018-01-07 03:11 UTC by tmc

2018-01-07 04:02 UTC, tmc commented
test comment

2018-01-07 04:03 UTC, tmc commented on .circleci/config.yml
> +    steps:
this is a test code comment

2018-01-07 04:34 UTC, tmc commented
@%v, it looks like there was a test failure, can you please investigate?

2018-01-07 04:35 UTC, tmc commented
@%v, it looks like there was a test failure, can you please investigate?

2018-01-07 04:36 UTC, tmc commented
@github.User{Login:"tmc", ID:3977, AvatarURL:"https://avatars1.githubusercontent.com/u/3977?v=4", HTMLURL:"https://github.com/tmc", GravatarID:"", Type:"User", SiteAdmin:false, URL:"https://api.github.com/users/tmc", EventsURL:"https://api.github.com/users/tmc/events{/privacy}", FollowingURL:"https://api.github.com/users/tmc/following{/other_user}", FollowersURL:"https://api.github.com/users/tmc/followers", GistsURL:"https://api.github.com/users/tmc/gists{/gist_id}", OrganizationsURL:"https://api.github.com/users/tmc/orgs", ReceivedEventsURL:"https://api.github.com/users/tmc/received_events", ReposURL:"https://api.github.com/users/tmc/repos", StarredURL:"https://api.github.com/users/tmc/starred{/owner}{/repo}", SubscriptionsURL:"https://api.github.com/users/tmc/subscriptions"}, it looks like there was a test failure, can you please investigate?

2018-01-07 04:36 UTC, tmc commented
@tmc, it looks like there was a test failure, can you please investigate?

2018-01-07 04:37 UTC, tmc commented
@tmc, it looks like there was a test failure, can you please investigate?

2018-01-07 04:38 UTC, tmc commented
@tmc, it looks like there was a test failure, can you please investigate?

2018-01-07 04:39 UTC, tmc commented
@tmc, it looks like there was a test failure, can you please investigate?

2018-01-09 07:20 UTC, redshiftzero commented
hehe ^^^^!@!!! @tmc

2018-01-10 04:59 UTC, redshiftzero requested changes
Major problems here. This is a test repo for one and this is a test review to check the bot Does a Good Thing

2018-02-28 12:03 UTC, closed without merging